config/routes.rb
# frozen_string_literal: true

Alerter::Engine.routes.draw do
  resources :alerts, only: %i[index show destroy]
end

app/models/alerter/alert.rb
# frozen_string_literal: true

module Alerter
  class Alert < ApplicationRecord
    self.table_name = 'alerts'

    belongs_to :source,
               polymorphic: true

    belongs_to :target,
               polymorphic: true

    belongs_to :object,
               polymorphic: true,
               optional: true

    validates :source,
              presence: true

    validates :target,
              presence: true

    validates :key,
              presence: true,
              allow_blank: false

    validates :object,
              presence: false,
              allow_blank: false,
              allow_nil: true

    def message
      Message.for(self).to_s
    end

    alias to_s message
  end
end

app/models/alerter/application_record.rb
# frozen_string_literal: true

module Alerter
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/controllers/alerter/alerts_controller.rb
# frozen_string_literal: true

require_dependency 'alerter/application_controller'

module Alerter
  class AlertsController < ApplicationController
    before_action :set_alert, only: %i[show destroy]

    # GET /alerts
    def index
      @alerts = Alert.all
    end

    # GET /alerts/1
    def show; end

    # DELETE /alerts/1
    def destroy
      @alert.destroy
      redirect_to alerts_url, notice: 'Alert was successfully destroyed.'
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_alert
      @alert = Alert.find(params[:id])
    end
  end
end

app/controllers/alerter/application_controller.rb
# frozen_string_literal: true

module Alerter
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/helpers/alerter/alerts_helper.rb
# frozen_string_literal: true

module Alerter
  module AlertsHelper
  end
end

app/helpers/alerter/application_helper.rb
# frozen_string_literal: true

module Alerter
  module ApplicationHelper
  end
end

app/views/alerter/alerts/_form.html.erb
<%= form_for(alert) do |f| %>
  <% if alert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(alert.errors.count, "error") %> prohibited this alert from being saved:</h2>

      <ul>
      <% alert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :source_id %>
    <%= f.number_field :source_id %>
  </div>

  <div class="field">
    <%= f.label :source_type %>
    <%= f.text_field :source_type %>
  </div>

  <div class="field">
    <%= f.label :target_id %>
    <%= f.number_field :target_id %>
  </div>

  <div class="field">
    <%= f.label :target_type %>
    <%= f.text_field :target_type %>
  </div>

  <div class="field">
    <%= f.label :source_url %>
    <%= f.text_field :source_url %>
  </div>

  <div class="field">
    <%= f.label :target_url %>
    <%= f.text_field :target_url %>
  </div>

  <div class="field">
    <%= f.label :message %>
    <%= f.text_field :message %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alerter/alerts/edit.html.erb
<h1>Editing Alert</h1>

<%= render 'form', alert: @alert %>

<%= link_to 'Show', @alert %> |
<%= link_to 'Back', alerts_path %>

app/views/alerter/alerts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alerts</h1>

<table>
  <thead>
    <tr>
      <th>Source</th>
      <th>Source type</th>
      <th>Target</th>
      <th>Target type</th>
      <th>Source url</th>
      <th>Target url</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alerts.each do |alert| %>
      <tr>
        <td><%= alert.source_id %></td>
        <td><%= alert.source_type %></td>
        <td><%= alert.target_id %></td>
        <td><%= alert.target_type %></td>
        <td><%= alert.source_url %></td>
        <td><%= alert.target_url %></td>
        <td><%= alert.message %></td>
        <td><%= link_to 'Show', alert %></td>
        <td><%= link_to 'Edit', edit_alert_path(alert) %></td>
        <td><%= link_to 'Destroy', alert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alert', new_alert_path %>

app/views/alerter/alerts/new.html.erb
<h1>New Alert</h1>

<%= render 'form', alert: @alert %>

<%= link_to 'Back', alerts_path %>

app/views/alerter/alerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Source:</strong>
  <%= @alert.source_id %>
</p>

<p>
  <strong>Source type:</strong>
  <%= @alert.source_type %>
</p>

<p>
  <strong>Target:</strong>
  <%= @alert.target_id %>
</p>

<p>
  <strong>Target type:</strong>
  <%= @alert.target_type %>
</p>

<p>
  <strong>Source url:</strong>
  <%= @alert.source_url %>
</p>

<p>
  <strong>Target url:</strong>
  <%= @alert.target_url %>
</p>

<p>
  <strong>Message:</strong>
  <%= @alert.message %>
</p>

<%= link_to 'Edit', edit_alert_path(@alert) %> |
<%= link_to 'Back', alerts_path %>

app/views/layouts/alerter/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sp alerts</title>
  <%= stylesheet_link_tag    "alerter/application", media: "all" %>
  <%= javascript_include_tag "alerter/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>